steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'europe-west9-docker.pkg.dev/microservices-shop-nestjs/image-registry/client-gateway-prod',
        '-f',
        'dockerfile.prod',
        '--platform=linux/amd64',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'europe-west9-docker.pkg.dev/microservices-shop-nestjs/image-registry/client-gateway-prod',
      ]
options:
  logging: CLOUD_LOGGING_ONLY
